### ISSUE TITLE
Swift - casting to date not working as expected 

### ISSUE THREAD

**Issue by pkasson** [duckdb/duckdb-swift#5]
The expectation of the following code should result in a date, as it is in the CSV, which is mm/dd/yyyy. Instead, it shows as Date(days: 19970)

'''
case .date:
TabularData.Column(self.cast(to: Date.self)).eraseToAnyColumn()
'''

The cast is not working - how do you fix this ?

To Reproduce

Unknown

OS:

MacOS 14.4.1

DuckDB Version:

0.10.3

DuckDB Client:

Swift

Hardware:

Macbook

Full Name:

0.10.3

Affiliation:

None

What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

Did you include all relevant data sets for reproducing the issue?

Yes

Did you include all code required to reproduce the issue?

 Yes, I have

**Comment by willtemperley** [comment]
I assume you're importing DuckDB and Foundation? If so, you're attempting to cast from DuckDB.Date to Foundation.Date.

duckdb-swift uses it's own `Date` type and works according to the SQL standard, counting days from 1970-01-01 [1].

It's fairly easy to pull out the date as a DuckDB.Date, then create a Foundation.Date from this:

```
    let date = df.columns[0].assumingType(DuckDB.Date.self)
    let foundationDate = Date(timeIntervalSince1970: TimeInterval(date.days * 86400))
```

[1] https://duckdb.org/docs/sql/data_types/date

**Comment by pkasson** [comment]
Thanks for the great insight ... new to DuckDB.  

In the extension to format the column properly, I dont see how to what you described, as the example I am using, which works so far for other data types, does not:

`
public extension DuckDB.Column
{
 var column: TabularData.AnyColumn
 {
  switch underlyingLogicalType.dataType
  {
   case .varchar, .uuid:
    TabularData.Column(self.cast(to: String.self)).eraseToAnyColumn()
    
   case .integer, .bigint, .uinteger, .ubigint:
    TabularData.Column(self.cast(to: Int.self)).eraseToAnyColumn()
    
   case .double, .float, .decimal:
    TabularData.Column(self.cast(to: Double.self)).eraseToAnyColumn()
    
   case .date:
    TabularData.Column(self.cast(to: DuckDB.Date.self)).eraseToAnyColumn()

   case .timestamp:
    TabularData.Column(self.cast(to: Timestamp.self)).eraseToAnyColumn()

   default:
    TabularData.Column(self).eraseToAnyColumn()
   }
  }
`

**Comment by willtemperley** [comment]
I'm new to DuckDB too and not a developer of this library. Could you format your code properly please? It's hard to read. Just highlight and click the angle bracket in the toolbar.

Does the code above run? Once you get hold of a ` DuckDB.Date` instance you can just convert to Foundation dates like so:

`let foundationDate = Date(timeIntervalSince1970: TimeInterval(duckDBDate.days * 86400))`

**Comment by stensoosaar** [comment]
Maybe the following code will help you:
```
let response = try connection.query(/**/)
let dateColumn = response[0].cast(to: DuckDB.Date.self)
var frame = DataFrame(columns: [
	TabularData.Column(dateColumn).eraseToAnyColumn(),
])			
frame.transformColumn("date") { (duckDate: DuckDB.Date) -> Foundation.Date in
	return Foundation.Date(duckDate)
}
´´´

**Comment by pkasson** [comment]
> I'm new to DuckDB too and not a developer of this library. Could you format your code properly please? It's hard to read. Just highlight and click the angle bracket in the toolbar.
> 
> Does the code above run? Once you get hold of a ` DuckDB.Date` instance you can just convert to Foundation dates like so:
> 
> `let foundationDate = Date(timeIntervalSince1970: TimeInterval(duckDBDate.days * 86400))`

I reformatted it ... sorry about that.

**Comment by pkasson** [comment]
> Maybe the following code will help you:
> 
> ```
> let response = try connection.query(/**/)
> let dateColumn = response[0].cast(to: DuckDB.Date.self)
> var frame = DataFrame(columns: [
> 	TabularData.Column(dateColumn).eraseToAnyColumn(),
> ])			
> frame.transformColumn("date") { (duckDate: DuckDB.Date) -> Foundation.Date in
> 	return Foundation.Date(duckDate)
> }
> ´´´
> ```

Awesome - that fixed it .. thank you !!!
